spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xuyafei
    url: jdbc:mysql://127.0.0.1/cell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /var/log/tomcat/sell.log
#  level: debug